### ISSUE TITLE
[doc] 6.9.7.2  Worker Node Certificate Rotation - how does this work without kucero running on the workers?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1011]
6.9.7.2  Worker Node Certificate Rotation:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_worker_node_certificate_rotation

--------------------
Can we get more clarification in this section? I can see that the kucero addon is just running on the masters - so how does the certificate get upgraded on the workers?

**Comment by r0ckarong** [comment]
@jenting

**Comment by jenting** [comment]
> 6.9.7.2 Worker Node Certificate Rotation:
> 
> https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_worker_node_certificate_rotation
> 
> Can we get more clarification in this section? I can see that the kucero addon is just running on the masters - so how does the certificate get upgraded on the workers?

The worker node control plane certificates are kubelet _client_ and _server_ certificate.
From up to now skuba release, we have address renew kubelet client certificate, however, for kubelet server certificate, we'll address it in the next coming release.

Generally:
- kubelet client certificate: the client CSR issue from kubelet daemon, the CSR signer and approver is the `kube-controller-manager`.
- kubelet server certificate: the server CSR issue from kubelet daemon, the CSR signer and approver is the `kucero`.

Therefore, kucero running on master nodes only is because it renews kubeadm-managed certificate/kubeconfgs, and we'll have enhancement for the kubelet server certificate on both control plane node and worker node in the next coming release.
