### ISSUE TITLE
[doc] 3.1.3  Applying Updates

### ISSUE THREAD

**Issue by gfigueira** [SUSE/doc-caasp#142]
Nowhere in this document, the registration process is described. It is possible (to what effect I don't know) to use SUSEConnect or transactional-update to register a system against SCC. The correct order the cluster has to be registered and update is also not found here.

3.1.3  Applying Updates

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#sec.admin.software.transactional-updates.installation

**Comment by r0ckarong** [comment]
Registering nodes is described in the deployment guide: 
https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.configuration.suseconnect

It makes sense to add a note to the update section referring to this section because you won't be able to install updates without registering.

**Comment by nkoranova** [comment]
https://github.com/SUSE/doc-caasp/pull/203
