### ISSUE TITLE
Create supported scenarios matrix

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#194]
Platforms
Scenarios
Configurations
Air gapped
Own Registry

**Comment by stefsuse** [comment]
Suggestion: Helm charts from https://kubernetes-charts.suse.com

Configuration can get complicated fast. Do you think it would be useful to include more generic reminders, ie 
"ensure any node level memory or cpu contraints >= constraints set in application manifest." ?

**Comment by NunoFilipeSantos** [comment]
@qnetter Can you please clearly describe the desired outcome of this?

**Comment by qnetter** [comment]
Since @r0ckarong opened it, I'm not sure exactly. But I would say that, for GA, @stefsuse's guidance is a good start. We should call out minimum and recommended resources - nodes, CPU, memory, storage. 

As to specific scenarios, I think we should cover that in the SE review, or seed the discussion - I will gladly kick that off.

Airgap and private-registry configurations will not be supported till post-GA so can be added post-GA.

**Comment by jordimassaguerpla** [comment]
About hardware requirements, this is already covered at https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_hardware

**Comment by NunoFilipeSantos** [comment]
Like @jordimassaguerpla said, HW we are covered. This is why I was trying to understand if, for now, we were still missing something @qnetter .

**Comment by stefsuse** [comment]
Thanks for the HW link. I was thinking more along the lines of the charts themselves when I said memory and cpu requirements (among other things like storage). For example, if a client wants a large number of smaller nodes they should be aware of the chart requirements. Some applications may not work though we generally support the deployment and the images.
