### ISSUE TITLE
Add legal includes to guides

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#212]
Rework the common includes:

- Disclaimer
- Copyright / Licenses
- About
- Feedback
- Doc Conventions
- Required Background

And add to all guides

**Comment by nkoranova** [comment]
@r0ckarong I propose we add all of those sections except the "About the Making of This Documentation" section, which is about SUSEDoc and XML, which is not relevant to us and probably also mostly not the SUSE toolchain, since we use adoc. There aren't any legal reasons why we should keep this, right? 
I can add the document and just comment out the include line.

**Comment by r0ckarong** [comment]
@nkoranova The "About" section needs to be rewritten for our new approach.

Please just create a new GitHub issue "Rewrite About Section" for this. We can tackle this later. You can leave it out for now.

**Comment by nkoranova** [comment]
#224
