### ISSUE TITLE
Edit Documentation conventions

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#220]
Some documentation conventions from Docbook XML are not relevant for Asciidoc. The Documentation Conventions section contains those conventions which we present to the reader. Decide on ASCIIDoc documetation conventions and edit/remove them in common_intro_typografie_i.adoc.

**Comment by r0ckarong** [comment]
While working on this also rename this file to `_typography.adoc` to remove the German remnant.

**Comment by r0ckarong** [comment]
Also remove the trailing `_i` from the filenames. This is probably meant to show that some files are "includes". In AsciiDoc any file can be an include file so this is pointless here.

**Comment by nkoranova** [comment]
done in  #224 https://github.com/SUSE/doc-caasp/pull/224/commits/399d2200b42d65235b5fb762d7b7be8597874394

**Comment by nkoranova** [comment]
Sorry to reopen this again, but I feel like aside from the renaming files and what I have edited before, there are still a couple of minor things here: 
*  "This paragraph is only relevant for the {amd64} /{intel64} architecture." - this can probably be deleted unless there is a good alternative for it in ASCIIDoc? 
* "This paragraph is only relevant for the architectures `{zseries}` and ``{power}``." same issue as the point above.
*  Is there a good way in ASCIIDoc to show that the user has to run the command as root? 
```
[source,bash]
----
{prompt_root} command
{prompt_user} sudo command
----
```
I think this doesn't really display well, so we should probably see if we can do that differently.

**Comment by r0ckarong** [comment]
1. Removed this
2. Same
3. I already fixed this in the file, what is needed here was to enable substitution of the entities in the code examples. You need to add the option `subs=attributes` to the source block parameters. This then will take any `{attribute}` notations and replace them with the known attribute value (from entities.adoc most of the time. 

This can cause some problems with some code examples and characters in the examples because they are misinterpreted by asciidoc, there are several [flags you can set for this parameter](https://asciidoctor.org/docs/user-manual/#applying-substitutions) to work around these issues. Probably typing out the prompt in text in these cases makes more sense. 

This is unfortunately an effect of the way substitutions are detected in AsciiDoc.
