### ISSUE TITLE
Documentation: Improve ssh-agent section

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/doc-caasp#245]
The documentation assumes that a key already exists and that is already shared across all nodes. We'd need to document or mention generating a key and copying it to the relevant nodes. It also forgets to mention where to run the ssh-agent. This was the most frustrating part of testing  CaaSP.

**Comment by r0ckarong** [comment]
The key should be distributed via terraform.

I will look at the other points.

**Comment by nkoranova** [comment]
This is the section we have on the ssh-agent: 
https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#deployment.preparations 
duplicate information is also here: 
https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_cluster_deployment 

We need to add: 
- [ ] how to add the key to all the nodes. 
- [ ] where to run the ssh-agent 

@jordimassaguerpla, who could help me with this?

**Comment by drpaneas** [comment]
> This is the section we have on the ssh-agent:
> https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#deployment.preparations
> duplicate information is also here:
> https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_cluster_deployment
> 
> We need to add:
> 
> * [ ]  how to add the key to all the nodes.
> * [ ]  where to run the ssh-agent
> 
> @jordimassaguerpla, who could help me with this?

I can help you with that.

> * [ ]  how to add the key to all the nodes.
This is done by skuba. You have to copy-paste the key [you previously added to the ssh-agent](https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#deployment.preparations) into your tfvars file as described [here](https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_deploying_the_cluster_nodes) and number 7. So all the information are already existing in the current documentation. Maybe you want to highlight that again or rephrase it. _e.g._ maybe at the 7. bulltet-point you can have a hyperlink reminding the user to add not just _any_ key but the key the ssh-agent is using.

> * [ ]  where to run the ssh-agent
This has to run from the same terminal session you are going to run the skuba commands. Every time you close that terminal and you open a new one you have to create again a new ssh-agent and add the key. There is also a better way by putting ssh-agent to run when the operating-system runs, so every terminal has it running already.

If you need more information let me know.

**Comment by jordimassaguerpla** [comment]
@drpaneas Thanks!

**Comment by bergmannf** [comment]
The information about the `operating system runs` is incorrect - the `ssh-agent` in case of big desktop environments use coupled to their `key-management` services, so `gnome`, `kde`, `mate` asf start those on the user login and will automatically add the `ssh-key` usually.

**Comment by abonillasuse** [comment]
Why is this request taking so long to implement? Can we just reference that customers should

# eval `ssh-agent`
# ssh-add

In the documentation?

I wrote this on #394 - unless there is going to be a more sane way to do this, which is unlikely at this version of CaaSP.

**Comment by jordimassaguerpla** [comment]
> Why is this request taking so long to implement?

Because this is not the only doc we have to fix/write ;)

We flagged this as P2, so this is in our top priority list.

 Can we just reference that customers should
> # eval `ssh-agent`
> # ssh-add
> 
> In the documentation?
> 
> I wrote this on #394 - unless there is going to be a more sane way to do this, which is unlikely at this version of CaaSP.

@abonillasuse Is this https://github.com/SUSE/doc-caasp/issues/245#issuecomment-519861671 enough?

**Comment by dannysauer** [comment]
I'm a little concerned about offering advice on running an ssh key agent which continues running for any particular period of time.  We're telling customers to load their private ssh key material - with any password controls removed - into a potentially long-running program whose access is controlled only by filesystem permissions on the socket.  We need to be careful to also provide information on the risk of running ssh-agent (or gpg-agent, or gnome-keyring, or whatever) if we're telling people to use those tools in a certain way.  What's mostly fine on a single-user workstation is potentially far less fine on a shared headless jump host at a large enterprise.  Same concern re: agent forwarding, though we do at least say to see the man page for that. :)

If we're providing an example, the documented command should probably just be `eval $(ssh-agent)`, since backticks have been deprecated in most Bourne shells for years. ;)  And the `-s` in the docs now should be removed because ssh-agent figures out if the shell is bourn or csh, and almost always generates the right thing.

There's also an error in the documentation: you can't actually add "as many keys to an agent as you want" and have things work.  Each key attempted counts as an authentication attempt against the remote host.  So, if an agent has more keys than the server's max authentication attempts parameter (we default to 6; it's not uncommon for sites to set it to 3), the user only gets in if the right key is in the first N attempted.  There are ways to specify which key(s) from an agent get attempted, but those are handled by the client and skuba & Terraform don't implement such control yet. :/  I'd like to see skuba support auto-adding keys on-demand to an agent the way OpenSSH `AddKeysToAgent yes` can do (thus facilitating running it like `ssh-agent skuba --arg --arg2`) and to support something like the OpenSSH `IdentitiesOnly` parameter, but that's a discussion for a different forum.

**Comment by jordimassaguerpla** [comment]
> I'm a little concerned about offering advice on running an ssh key agent which continues running for any particular period of time. We're telling customers to load their private ssh key material - with any password controls removed - into a potentially long-running program whose access is controlled only by filesystem permissions on the socket. We need to be careful to also provide information on the risk of running ssh-agent (or gpg-agent, or gnome-keyring, or whatever) if we're telling people to use those tools in a certain way. What's mostly fine on a single-user workstation is potentially far less fine on a shared headless jump host at a large enterprise. Same concern re: agent forwarding, though we do at least say to see the man page for that. :)
> 
> If we're providing an example, the documented command should probably just be `eval $(ssh-agent)`, since backticks have been deprecated in most Bourne shells for years. ;) And the `-s` in the docs now should be removed because ssh-agent figures out if the shell is bourn or csh, and almost always generates the right thing.
> 
> There's also an error in the documentation: you can't actually add "as many keys to an agent as you want" and have things work. Each key attempted counts as an authentication attempt against the remote host. So, if an agent has more keys than the server's max authentication attempts parameter (we default to 6; it's not uncommon for sites to set it to 3), the user only gets in if the right key is in the first N attempted. There are ways to specify which key(s) from an agent get attempted, but those are handled by the client. Unfortunately, skuba & Terraform don't implement such control yet. :/ I'd like to see skuba support auto-adding keys on-demand to an agent the way OpenSSH `AddKeysToAgent yes` can do (thus facilitating running it short-lived like `ssh-agent skuba --arg --arg2`) and to support something like the OpenSSH `IdentitiesOnly` parameter, but that's a discussion for a different forum.

@dannysauer Please create a PR to the doc-caasp repo with the modifications so doc team can review it. This issue is becoming confusing with so many comments and seems you know how this should look like. This would be very helpful. Thanks.

**Comment by dannysauer** [comment]
I figured with all that discussion, someone had already started on it. If that's not the case, I'll write up a PR other people can tear apart then. :)

**Comment by jordimassaguerpla** [comment]
> I figured with all that discussion, someone had already started on it. If that's not the case, I'll write up a PR other people can tear apart then. :)

Yes please :)

**Comment by nkoranova** [comment]
Issue solved in #409 Thanks for your contributions. :)
