### ISSUE TITLE
update how to obtain the reg code master deployment (and quickstart) guide

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#249]
From now on, the reg code needs to be requested to the beta program as explained in the beta documentation.

Can you update the docs in master as well?

**Comment by vmoutoussamy** [comment]
Please replace :

> You need a subscription registration code to use SUSE CaaS Platform. You can retrieve your registration code from SUSE Customer Center.
> 
>     Login to https://scc.suse.com
>     Navigate to Internal tools › Products
>     Search for "caasp"
>     Select SUSE CaaS Platform › 4.0 › x86_64 alpha
>     Copy the Registration Code

By 

> If you wish to beta test SUSE CaaS Platform 4, please send an e-mail to beta-programs@lists.suse.com to request a SUSE Customer Center subscription and a registration code.

Why ? because the former is available only to SUSE Employee (for now), the later is fine for both public/internal because then we (me)  can forward codes from the public beta pool to the public and the former speech to internal.

NOTE: Of course this should be replaced by "something else" for GA.

**Comment by jordimassaguerpla** [comment]
This is not needed any more.
