### ISSUE TITLE
Make it more obvious the reg code is caasp and not sle

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/doc-caasp#250]
From Section 3.1.2, we use "REGISTRATION_CODE"

This is confusing for customers because they are requesting SLE15SP1 registration codes.

Can we make it more obvious? What about replacing it by "CAASP_REGISTRATION_CODE" in the examples?

**Comment by vmoutoussamy** [comment]
Overall I think this need more attention and maybe PM input. Because CaaSP regcode gives both SLES and CaaSP channels AND it make no sense to me to note that you can register your SLES first >  "Activate SUSE Linux Enterprise (Skip if you already have an activated operating system)".

Still IMHO the perfect solution would have been that the user only need to do the following with a caasp regcodes: 
`sudo SUSEConnect -r REGISTRATION_CODE`
which automatically enable register and enable SLES, sle-module-containers/15.1/x86_64 and caasp/4.0/x86_64. 

Is this possible for caasp4.0 or in the future?
Can someone check what happened if one only do `sudo SUSEConnect -r CAASP_REGISTRATION_CODE`?

**Comment by r0ckarong** [comment]
Ok I will reword this and spam the CaaSP name.

**Comment by vmoutoussamy** [comment]
FYI: What's in the code of skuba for registration https://github.com/SUSE/skuba/blob/1a302d0743b86c53d24a43d309071c0131b47953/ci/infra/openstack/cloud-init/register-scc.tpl

**Comment by nkoranova** [comment]
I finally get to this, but I am slightly confused about what the underlying system is. @vmoutoussamy can confirm that if this is correct:
The way I understand it according to our [documentation ](https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#registration_code ) is that there is just one registration code both for SLE and for CaaSP: "You can use your SUSE CaaS Platform registration code to activate the SUSE Linux Enterprise 15 SP1 subscription during installation. " The placeholder`REGISTRATION_CODE` only refers to the CaaSP, so it makes sense to rename it to `CAASP_REGISTRATION_CODE`.  

What confuses me is this: "(Skip if you already have an activated operating system)" - can we just delete that? We have just told the reader that he needs to activate both and now they have somehow miraculously already activated it? :)

**Comment by vmoutoussamy** [comment]
> I finally get to this, but I am slightly confused about what the underlying system is. @vmoutoussamy can confirm that if this is correct:
> The way I understand it according to our [documentation ](https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#registration_code) is that there is just one registration code both for SLE and for CaaSP: "You can use your SUSE CaaS Platform registration code to activate the SUSE Linux Enterprise 15 SP1 subscription during installation. " The placeholder`REGISTRATION_CODE` only refers to the CaaSP, so it makes sense to rename it to `CAASP_REGISTRATION_CODE`.

I assume this is correct, but please note that I didn't test it lately, it would be better to double check with @jordimassaguerpla for both the beta and official regcodes.

> What confuses me is this: "(Skip if you already have an activated operating system)" - can we just delete that? We have just told the reader that he needs to activate both and now they have somehow miraculously already activated it? :)

I think we should. But my assumption is if you register a SLES with regcode A, but then install the CaaSP product and uses regcode B. Your system doesn't use regcode A anymore but only regcode B which supply SLES and CaaSP repos. Again, I'm no CaaSP expert, this would require testing, but if it's true maybe it still deserve a small note to warn the customer. Since customer buy our subscriptions/regcodes, it is important to be clear.
