### ISSUE TITLE
Review CAP POC documentation

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#264]
Cameron Seader provided a step-by-step document describing the manual deployment process on OpenStack. Review what we already cover and integrate into the deployment instructions were possible.

**Comment by jordimassaguerpla** [comment]
@drpaneas will provide you with more recent docs https://github.com/SUSE/avant-garde/issues/397

**Comment by nkoranova** [comment]
I am not sure that this entirely covers what @r0ckarong intended to do with that step-by-step document by Cameron Seader. Does anyone know where that document can be found? I couldn't find it in confluence.

**Comment by nkoranova** [comment]
https://github.com/SUSE/doc-caasp/pull/397

**Comment by nkoranova** [comment]
I got input from Panos about the `--strict-cap-defaults` flag and working on integrating the info into the deployment guide.

**Comment by nkoranova** [comment]
Ludo has provided Cameron's step-by-step guide.

**Comment by jordimassaguerpla** [comment]
This is 20 page document!!

**Comment by jordimassaguerpla** [comment]
This task is not needed anymore because of https://github.com/SUSE/avant-garde/issues/745 . @nkoranova please share the doc with Taiwan Team and see what can they reuse.

**Comment by innobead** [comment]
This document is incomplete.

1. For OpenStack infra, it uses manual way to setup instead of the terraform scripts provided by us
2. It describes more about Air-gapped environment, but this documentation is not ready and it was planned at `post-GA`. 
3. It does not provide CAP deployment steps
4. It mixed CaaSP v3 info inside
5. In summary, it is CaaSP deployment only (and based on `caaspctl`)

@jordimassaguerpla @nkoranova could you help confirm the source of CAP POC documentation again, and provide the complete version ready for review, then we can work on the review. Thanks.

cc @c3y1huang

**Comment by jordimassaguerpla** [comment]
Hi @innobead . The document was provided to us by a Sales Engineer but this does not mean it has to go into the docs as it is.

Please just reuse what you think makes sense (if any) for the CAP documentation. We thought this could be helpful, but if it turns out it is better to write from scratch on how to deploy CAP on top of CaaSP, then trash it and start from scratch.

Thanks

**Comment by nkoranova** [comment]
@innobead, I agree with @jordimassaguerpla. What is described in the document can be used as inspiration, but definitely take it with a grain of salt, as it's probably already outdated.

**Comment by innobead** [comment]
@jordimassaguerpla @nkoranova I don't agree actually, because this document is not CAP deployment documentation, and what we planned is for `review CAP documentation` that is different from creating a new documentation.

But let's move forward to solve the issue :)

Even we can come out the CAP deployment on v4, but this looks overlapped with CAP product documentation (https://www.suse.com/documentation/cloud-application-platform-1/book_cap_guides/data/cha-cap-depl-caasp.html) which describes how to deploy CAP on CaaSP v3.

For CAP deployment, It will be better to update CAP itself documentation instead of integrating into CaaSP documentation? (However I am not sure CAP doc release flow, but it definitely needs to update after v4 out)

@nkoranova please think of what kind of documentation for CAP you would like to integrate into doc-caasp? Will it be more about prerequisites for CAP deployment (what we encountered issues like cri-o default capabilities, swap settings, storage class, ...) or complete CAP deployment (overlapped with CAP itself documentation) or others? Let's clarify the definition first, before next step. Thanks.

**Comment by jordimassaguerpla** [comment]
@NunoFilipeSantos I think we need your input here

**Comment by NunoFilipeSantos** [comment]
I don't know where you have been looking at.
See https://github.com/SUSE/avant-garde/issues/397 and https://github.com/SUSE/doc-caasp/pull/397/files

**Comment by innobead** [comment]
> I don't know where you have been looking at.
> See [SUSE/avant-garde#397](https://github.com/SUSE/avant-garde/issues/397) and https://github.com/SUSE/doc-caasp/pull/397/files
> 

The PDF provided by Sales Engineer was @nkoranova shared yesterday to you, jordi and me.

> If even then you are struggling @drpaneas is one of the guys that spearheaded this topic on CaaSP v4.

@NunoFilipeSantos you did not get my point, please look at my previous comment or below.^ 

```
@nkoranova please think of what kind of documentation for CAP you would like to integrate into doc-caasp? Will it be more about prerequisites for CAP deployment (what we encountered issues like cri-o default capabilities, swap settings, storage class, ...) or complete CAP deployment (overlapped with CAP itself documentation) or others?
```
https://github.com/SUSE/doc-caasp/pull/397/files is about (--strict-cap-defaults) is part of prerequisites for CAP deployment.

**Comment by NunoFilipeSantos** [comment]
Setup of CaaS Platform and Cloud Application Platform a quick road to success for our customers.

**Comment by innobead** [comment]
> Setup of CaaS Platform and Cloud Application Platform a quick road to success for our customers.

Should this documentation be updated in doc-cap or doc-caasp? CAP production documentation already covers this part (https://www.suse.com/documentation/cloud-application-platform-1/book_cap_guides/data/cha-cap-depl-caasp.html) but it is for v3 like I mentioned above.

I would suggest let's just come out CAP integration documentation like we did for SES, but SES focus on `usage`, CAP will more focus on `prerequisites of CAP` before CAP deployment via helm charts which can be referenced to CAP itself deployment guide.

@jordimassaguerpla @NunoFilipeSantos @nkoranova ok?

**Comment by jordimassaguerpla** [comment]
@innobead 

I would expect this:

1- prerequisistes for CAP
2- simple deployment via helm charts
3- link to CAP docs for more details and/or complex deployments

In general, something short with references to CAP but at the same time useful to do a simple deploy because CAP docs are out of our hands.

**Comment by NunoFilipeSantos** [comment]
Exactly what @jordimassaguerpla said.

**Comment by innobead** [comment]
Yes, this is what I described. We are on the same page now, and definition clarified. Thanks.
