### ISSUE TITLE
[doc] Procedure&nbsp;2.6:  Set Up The External Mirror 

### ISSUE THREAD

**Issue by lnyiri63** [SUSE/doc-caasp#276]
Procedure&nbsp;2.6:  Set Up The External Mirror 

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#id-1.4.4.3.10.3.6

Step 8 part referencing to certificates is wrong based on command in step 9. Proper certificates placement (based on command in step 9) is /etc/docker/registry/certs
Step 8 contains wrong alignment of last option. It has to be aligned same way as options enabled, interval;

**Comment by r0ckarong** [comment]
This was a misunderstanding because of some outdated information. The folder "/registry/certs/" is never filled with anything. It was left over from a previous version of the instructions.

The only certificates required are the SMT server certificates that are generated during the setup of SMT and must be provided to the reverse proxy to function properly.

I will amend the documentation.

**Comment by r0ckarong** [comment]
I also fixed the alignment of the `threshhold` option.

**Comment by r0ckarong** [comment]
21edd1f + 18609c3
