### ISSUE TITLE
[doc] 2.2.2  Concepts

### ISSUE THREAD

**Issue by lnyiri63** [SUSE/doc-caasp#278]
2.2.2  Concepts

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.scenarios.airgap.concepts

Honestly, which network setup is most common? directly connected to the internet or air gaped? Neither. The most common scenario is connecting external mirror from behind firewall-ed proxy (with or without internal air gaped mirror). This scenario is missing at all. It has lot of configuration exceptions in reference to recent document. If someone would like to sell this solution, he / she has to supply the information allowing to be so.

**Comment by r0ckarong** [comment]
Can you provide additional information on the "firewalled proxy" scenario e.g. specific configuration exceptions?

**Comment by r0ckarong** [comment]
@kkaempf @qnetter @ereslibre Do we have any knowledge of this "most common" scenario?

**Comment by qnetter** [comment]
Who's the OP, by the way?

I agree that the configuration that uses HTTP(S) proxy to access the internet will be common. Several folks - Cameron, among others - have the info.

**Comment by r0ckarong** [comment]
> Who's the OP, by the way?

No idea. We get a lot of contributions from SUSE members that only stumble onto GitHub because our documentation portal links to this repository when you want to file a bug for the docs. Then I assume they create some GitHub account, never fill in details and then leave forever.

@qnetter @kkaempf So can I get a prio please when we need to describe this for v4 / v5 and backport to v3? The original question was in regards to 3 but I don't see us describing this there. For anything newer the details will have change so much we can't reuse anything. Let me know which version we need to describe this for and I will create a new issue.

**Comment by kkaempf** [comment]
No backport for v3. We will only fix L3s in v3 from now on.
The 'airgap' topic is scheduled for a future v4 sprint.
