### ISSUE TITLE
Describe node management

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#328]
- [x] Adding nodes
- [x] Removing nodes properly
- [x] Replacing nodes

**Comment by NunoFilipeSantos** [comment]
I think there is a typo on the beginning of the section here: https://susedoc.github.io/doc-caasp/beta/caasp-admin/single-html/#_cluster_management

@nkoranova shouldn't this guide complete this task?

**Comment by nkoranova** [comment]
@NunoFilipeSantos Well in my opinion this part is good enough, I wrote that chapter and Markus merged it. It's possible Markus wanted to somehow improve on it, because it is not very detailed, but it contains all the info I got from developers and I would need some more input/feedback to be able to tell if/how this needs improving.

**Comment by nkoranova** [comment]
Fixed the typo with https://github.com/SUSE/doc-caasp/commit/5a6038aba88e06ba55ecb9e273f3f83e523f5f44 thanks!

**Comment by NunoFilipeSantos** [comment]
@nkoranova The node management seems described as it stands. Please close the issue as there are no clear questions for the engineering team.
