### ISSUE TITLE
Describe Backup

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#331]
Describe how to backup the cluster.

Scope for backup must be defined by PM/PO. Customer expectation is full configuration and workload backup.

**Comment by r0ckarong** [comment]
@kkaempf @qnetter @NunoFilipeSantos Could you please define the official scope of CaaSP v4 backup.

Same topic as for v3

* Technology
* Scope
* Full cluster or single nodes
* If/How to preserve configurations and workloads

**Comment by kkaempf** [comment]
I do not think we should document backup of individual nodes. It's a cluster and nodes are expected to die.

We probably can restrict it to pointing to SLE best practices of backing up the admin node (where terraform/skuba runs) configurations.

cc @flavio

**Comment by flavio** [comment]
Yes, I agree. However we still need to have a document that explains what to do when there's a partial cluster failure. For example, what to do if one of these cases happens:

  * One of the worker nodes just fails (due to a terrible hardware failure)
  * One of the master nodes fails, but the etcd quorum is not lost

If I'm not mistaken these are the scenarios that we covered inside of the documentation of v3 as part of the "backup story".

I'm not sure we had something inside of this story about how to do backups of the etcd database. This is usually something not needed, as long as you do not end up in:

  * You lost the majority of your etcd cluster: what to do from there?
  * You lost all the master nodes (hence all the etcd cluster)

These are cases we should cover as well, but I would give the priority to making sure that what we had documented for v3 is available also to v4 (with the relevant cases, for example the backup of the admin node is no longer necessary, because there's no admin node :smile:).

**Comment by qnetter** [comment]
We need to document a procedure to restore the cluster if it disappears. In the absence of a dedicated admin node, we need to back up what it would take to re-bootstrap it with the original configuration, including all of the etcd data. Backup of containers themselves can be out of scope of the instructions.
