### ISSUE TITLE
[doc] 3.3.2.2  Preparation of the VM as a template

### ISSUE THREAD

**Issue by rdannert** [SUSE/doc-caasp#391]
3.3.2.2  Preparation of the VM as a template

https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_preparation_of_the_vm_as_a_template

I am not sure, if the cloud-init related systemd files should be used for VMware

  systemctl enable cloud-init cloud-init-local cloud-config cloud-final

**Comment by bergmannf** [comment]
@jordimassaguerpla AFAIR without enabling those `cloud-init` did run into problems and did not complete successfully, which is why we added them to the documentation.

@lcavajani Do you remember which part of `cloud-init` failed without them?

**Comment by thehejik** [comment]
For unattended caasp v4 terraform deployment on vmware it is mandatory to enable cloud-init services, otherwise it wouldn't work.

I took these services from OpenStack JeOS where cloud-init is involved by default in JeOS, see https://build.suse.de/package/view_file/SUSE:SLE-15-SP1:GA/kiwi-templates-SLES15-JeOS/images.sh?expand=1

If you are not going to use terraform on vmware (for auto deployment) you can prepare the VM template semi-automatically by using autoyast profile for bare-metal and you don't need the cloud-init at all. 

But then you'd need to deploy each VM from the template manually in vSphere UI. In this case it is also mandatory to perform the machine-id & repos cleanup in the template and then regenerate the machine-id and register to SCC again on newly deployed VMs.

I believe this issue is INVALID.

**Comment by Martin-Weiss** [comment]
> For unattended caasp v4 terraform deployment on vmware it is mandatory to enable cloud-init services, otherwise it wouldn't work.
> 

Could you explain why this is the case with terraform or in general? 

AFAIK VMware supports VM personalization using vmware-tools / open-vm-tools in the guest and with templating in VMware - so why is cloud-init required in addition within the templates?

**Comment by thehejik** [comment]
Right, there are also other methods for data injection into vmware VM (AFAIK based on GuestInfo channel or ESX API - pyvmomi; ignition as replacement for cloud-init) which are not depending on cloud-info services nor Terraform itself.

Anyway, for CaaSP v4 we are providing vmware terraform states based on our terraform states used on OpenStack with official cloud-init support (JeOS-cloud-init image exists for it).

Hence for vmware we are describing how to prepare VM template which is similar to JeOS image for OpenStack with cloud-init services enabled.

**Comment by Martin-Weiss** [comment]
Do you know why with Terraform and VMware the open-vm-tools are not sufficient and why cloud-init is required in this area, too? Do we prevent somehow that not both try to adjust the servers identity?

**Comment by Martin-Weiss** [comment]
Ok - thanks. Customer does not want to use terraform because they already have their VMware machine provisioning infrastructure based on powershell and VMware API - so we are trying to find out what exactly we need in the VM guests for templating and using VMware based personalization.. assuming that open-vm-tools should be sufficient.. but I agree - this is a slightly different usecase.

**Comment by nkoranova** [comment]
It looks like this issue in indeed irrelevant. I'll go ahead and close it then.
