### ISSUE TITLE
[doc] 3.1  Cluster Size Requirements

### ISSUE THREAD

**Issue by escrevebastante** [SUSE/doc-caasp#437]
3.1  Cluster Size Requirements

https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_deployment/book_caasp_deployment.html#sec.deploy.requirements.system.cluster

I would like to open a discussion here regarding this statement specifically:

> "The minimum supported cluster size is four nodes: a single administration node, one master node, and two worker nodes. " 

I don't think that we should support a 4 node cluster setup. This setup implies that the worker nodes are also members of etcd cluster. In this setup, if customer manually patches and reboot one of the worker nodes, for example, he might run into issues. Etcd operation should be completely isolated from any workload that the workers are running. Sure, customers can deploy a 4 node cluster but if they do, they are on their own. Let me explain the reason for that in details:

We are facing more and more customers that deploy a 4 nodes setup initially for testing and then carry the same setup for production without increasing the node number and then run into issues later. In some cases, even when they do increase the master node number in the cluster, etcd membership on the previous setup for worker nodes doesn't change and I think that this whole setup shouldn't be officially supported. In my view, the minimum supported cluster size should be six nodes: 1 admin, 3 masters (for minimum etcd resilience operations) and 2 workers. 

So my suggestion here would be:

1 - Remove the word "supported" on this frase

OR

2 - Change the minimum supported cluster size from 4 to 6

**Comment by stefsuse** [comment]
I agree that the wording is misleading. Removing the word "supported" is a good start. Maybe we should remove "Note: Test and Proof-of-Concept Clusters" too since it also implies the 4 node setup is somehow more supported. 

The related release notes section is better, but for consistency that note can be removed and the minimum production cluster (3 master, 2 worker) added. https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/3.0/#Intro.Requirements.Cluster

**Comment by r0ckarong** [comment]
@qnetter @kkaempf This discussion must happen on the PM/PO level. We specifically worded this for 4 nodes because there was complaints that anything larger would scare away some customers. I can not make this call on what is "supported" or can be even called "supported" for marketing reasons.

Please define the official cluster minimum size. Same discussion needs to happen for v4.

**Comment by kkaempf** [comment]
Actually, PM can ask engineering to support specific scenarios, but the last word is on engineering.

Passing on to @flavio and @ereslibre :wink:
- which _minimal_ cluster size is supportable ?

**Comment by flavio** [comment]
So, the minimal size of a cluster with v4 is two nodes: 1 master and 1 worker.
We can support growing this minimal setup to something bigger. We won't however recommend its usage in a production environment: there's no HA anywhere in this picture.

To abstract it even further: we do not recommend the usage in production of any kind of cluster with less than 3 master nodes. That's because etcd is now deployed **only** on the master nodes. Hence we must have 3+ master nodes to have a HA deployment of etcd.

**Comment by ereslibre** [comment]
> So, the minimal size of a cluster with v4 is two nodes: 1 master and 1 worker.

Theoretically a single master node (without worker nodes) should suffice as the minimal-minimal, as long as they have the right tolerations in place for their workloads. Of course, as @flavio says, this is not a recommended setup for production.

**Comment by r0ckarong** [comment]
@flavio @ereslibre The question remains: What is the minimal "supportable" environment? In this context it means "What is the minimal cluster size you can run in production that we will provide _support_ for?" Support meaning, "We will fix our code/docs/processes if your workloads won't run on that configuration".

@kkaempf Am I misunderstanding what we mean with "supported". It's certainly the expectation customers have and I agree with Pedro that we should not call anything "supported" that can't be used in full production.

**Comment by kkaempf** [comment]
> Support meaning, "We will fix our code/docs/processes if your workloads won't run on that configuration".

Not really. The above sounds as "if you have a broken workload, we will fix caasp" (aka 'we adapt, you succeed' :grin:).

It's rather like "We will help you to get your workloads running and fix code/docs/processes if needed".

> 
> @kkaempf Am I misunderstanding what we mean with "supported". It's certainly the expectation customers have and I agree with Pedro that we should not call anything "supported" that can't be used in full production.

Yes, fully agreed.
On top of that, _supported_ is **always** an engineering decision. If engineering is not comfortable to support something, it shouldn't be flagged as supported (resp. not shipped as part of the product).

**Comment by r0ckarong** [comment]
Ok then I will reword to make it abundantly clear that while you CAN use a minimal configuration of as little as two machines, this is not supported or in any way ready for production. The new default minimal "supported" configuration will be adjusted to 6.

**Comment by flavio** [comment]
6, where is this number coming from?

The minimal supported configuration for production is going to be:
  *  3 master nodes
  * 1 worker node

There's no need to have an admin node with v4. They could run skuba from their laptop or from one of the master nodes. We would be fine with it.

**Comment by Martin-Weiss** [comment]
Why do we need one worker only? We have dex, gangway only running on workers - so 1 worker would not give fault tolerance... if we go down to one worker - why not go down to 1 master, too?

**Comment by ereslibre** [comment]
> Why do we need one worker only? We have dex, gangway only running on workers

On the first MU for skuba they tolerate running on master nodes as well.

**Comment by ereslibre** [comment]
> 6, where is this number coming from?

3+1

Plus, the two load balancers they should set up in order to be real HA, if they are using machines for setting up the LB's.

**Comment by Martin-Weiss** [comment]
I am still not happy with the wording "two load balancers" - this is like adding "two storage systems".
We need one load balancer that is as "fault tolerant" as the customer requires. This is also true for DNS, NTP, Storage. A single load balancer can have a higher availability than two load balancers that are somehow "interconnected".

Also I do not see why we should support a scenario with only a single worker - what is the sense of this? We recommend to run every POD at least twice so that a failure of a worker does not cause service-interruption... or is that wrong?

Also in general DNS, NTP, Storage and Load Balancer are not part of CaaSP - so IMO we should specify the minimum supported cluster size to 5 (3 masters + 2 workers). 
Everything else are dependencies "outside" of the cluster (management workstation for Skuba, Helm, Skopeo, Load Balancer, Storage, Network Cabling, DNS, NTP, Registry, Internet,.........).

**Comment by ereslibre** [comment]
> I am still not happy with the wording "two load balancers" - this is like adding "two storage systems".
We need one load balancer that is as "fault tolerant" as the customer requires

Agreed.

> Also I do not see why we should support a scenario with only a single worker - what is the sense of this? We recommend to run every POD at least twice so that a failure of a worker does not cause service-interruption... or is that wrong?

I would support that we document that only 2+ worker nodes clusters are supported.

> Also in general DNS, NTP, Storage and Load Balancer are not part of CaaSP - so IMO we should specify the minimum supported cluster size to 5 (3 masters + 2 workers).

This makes sense to me.

**Comment by ereslibre** [comment]
@Martin-Weiss the reason why I am recommending two LB's is that you don't have a single point of failure in any component. This is not achievable with just one. What's your suggestion here?

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss the reason why I am recommending two LB's is that you don't have a single point of failure in any component. This is not achievable with just one. What's your suggestion here?

If you by a storage system - the storage system has two storage "heads" and due to that provides fault tolerance. So from a logical point of view it is one storage system but it has two (or even more heads) making it fault tolerant from a client point of view.

For a load balancer this is the same - one load balancer can be fault tolerant internally and you can buy a single physical load balancer that also provides fault tolerance. So from a logical point of view we need one load balancer that must be fault tolerance (or provides an availability to the level the customer needs ) - but how this fault tolerant is build (applicance, in the box, sle-ha cluster, two or five physical load balancer machines) does not matter for CaaSP.

If we really would go down this road - we would also need to define "three data-centers" ;-). 
Oh - and btw. also one single k8s cluster can be seen as not fault tolerant  as a single command can destroy it - so we would need two or more ;-). 

For CaaSP or in general for fault tolerance we need to eliminate all relevant single point of failures a customer can afford - and today we use one load balancer in the majority of deployments and we rely on the load balancer to be implemented fault tolerant.

**Comment by ereslibre** [comment]
> If we really would go down this road - we would also need to define "three data-centers" ;-).
Oh - and btw. also one single k8s cluster can be seen as not fault tolerant as a single command can destroy it - so we would need two or more ;-).

I see your point. For the issue at hand then I think we can avoid adding up two load balancers to the cluster size requirements, because the customer will use their own means to perform a failover LB operation.

The question is for those customers that don't have the ability to set up such mechanisms (like buying F5 hardware); in those cases we can have a suggestion for a failover set up (my proposal was at least two LB's with VIP [keepalived?], but I don't know if we can publicly document that -- don't know our supportability status on keepalived for instance).

**Comment by Martin-Weiss** [comment]
I would not even go that deep - K8S needs a load balancer and that should have a high enough availability that fulfills the customers requirements.  If they do it via VMware HA or use keepalived or haproxy or what else - should not be our problem. We can just say that in case they are interested in a SUSE solution SLE-HA with pacemaker and haproxy can help to address their needs.
(keepalived is not yet included in SLE-HA)

**Comment by r0ckarong** [comment]
Changed wording once again to reflect this discussion:
https://github.com/SUSE/doc-caasp/commit/037aab1de1b1a4e74942fb95d5e255abb1e75913

**Comment by flavio** [comment]
Thanks @r0ckarong. I like the new wording
