### ISSUE TITLE
[doc] 4.1.2  Updating Nodes - details about process and load balancer management?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#502]
4.1.2  Updating Nodes

https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_updating_nodes
-----
Here we read this: "During the upgrade to a newer version, the API server will be unavailable so it is recommended to remove the node you are upgrading from the load balancer pool before the upgrade to avoid any connection issues."

--> could we be more clear with this? how do we have to handle the upgrade of the masters vs workers regarding the load balancer configuration?

3 masters - question if this is the right process:
1. remove master 1 from the load balancer
2. upgrade the master 1
3. add master 1 back to the load balancer even though it has a different version, now?
4. repeat 1..3 for master 2
5. repeat 1..3 for master 3
->  if that is true the whole message is not needed as the load balancer automatically handles the failure if one master is not available

Or do we need to keep API on newest version always:
1. remove master 1 from load balancer
2. upgrade master 1
3. change load balancer to use master 1 only
4. upgrade master 2+master3
5. change load balancer to use master 1+2+3

Or do we need to keep API via load balancer on oldest version until majority is new?

Btw. I believe the load balancer management during upgrades is not possible at all in real world deployments where the load balancers are managed by different teams than the clusters patchlevel / versioning..

**Comment by ereslibre** [comment]
There is no need to remove master nodes from the load balancer. If the load balancer performs active health checks and has a pool of active backends, it should remove from the pool and add back just fine.

Since we are enforcing that an upgrade goes from a minor version to the immediate next one (e.g. if you have to upgrade from 1.14 to 1.16, `skuba` will force you to go through 1.15), and taking into account the [Kubernetes version and skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/), it's fine to follow the first approach, even without removing nodes from the load balancer (as you comment on that option).

**Comment by Martin-Weiss** [comment]
Ok - thanks - then we should remove that sentence from the documentation about removing masters from the load balancer (Or change the sentence that the upgrade process requires a load balancer with active checks :-))

**Comment by r0ckarong** [comment]
Added with: https://github.com/SUSE/doc-caasp/commit/eb8fb83a91f74e183234adcbbad67a8d26210fd9
