### ISSUE TITLE
[doc] 2.2.1  Ports - which ports are required between admin / management host and the rest of the cluster?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#516]
2.2.1  Ports

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_ports

-------------------------
In scenarios where one admin/management node is used to manage multiple clusters it is pretty likely that this admin/management host is in a different network and can only reach the cluster (master, api, dex.....) via router and firewall.

Could we also add the information to the documentation which communication ways are required between the admin and the CaaSP cluster? (is ssh enough or do we also need API, DEX, Gangway an others?)

**Comment by r0ckarong** [comment]
@ereslibre Can you provide this information?

**Comment by ereslibre** [comment]
They need, at least:

* SSH access to all machines in the cluster
* Access to the apiserver (the load balancer will expose it), that will in turn talk to any master in the cluster
* Access to Dex in the nodeport (32000) using the load balancer when the OIDC token has expired, in order to renew it using the refresh token
