### ISSUE TITLE
Unify use of placeholders.

### ISSUE THREAD

**Issue by nkoranova** [SUSE/doc-caasp#538]
According to the [conventions defined in our guides](https://documentation.suse.com/suse-caasp/4/single-html/caasp-admin/#_documentation_conventions) and the [SUSE Style Guide](http://docserv.nue.suse.com/documents/Style_Guide/docu_styleguide/html/#sec-placeholder), placeholders for actual values are written in capitals: `PLACEHOLDER`. 
In reality we don't really adhere to this rule. The most established way of writing placeholders in our docs is inside angle brackets and lower case: `<placeholder>`. The use of separators in multi word placeholders is also not clear. I've seen periods, underscores, hyphens and spaces. 
Let's decide on a way to do it and stick to it.

**Comment by r0ckarong** [comment]
I translated the doc conventions roughly to what was available in AsciiDoc.

If we want to keep this aligned with the rest of the products we either lead by example (suggest we talk to the SUMA folks how they're handling this) or start a long discussion in the Doc team about how everyone thinks it should be handled. I'm for the former since we're the two projects that I know of that are actively working with Adoc.

**Comment by r0ckarong** [comment]
Adjust https://github.com/SUSE/doc-caasp/blob/master/adoc/common_intro_typography.adoc if necessary.

**Comment by r0ckarong** [comment]
As discussed settling on: `<variable_name>`
