### ISSUE TITLE
[doc] 5.2.2.1  Network Settings -> add a recommendation for size of service and pod network

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#593]
5.2.2.1  Network Settings

https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#_network_settings

---
I would recommend to specify /16 or bigger for the pod / overlay network (/16 allows up to 256*256 pods)
And I would recommend to specify a smaller network for the services as in general the number of services can be expected to be smaller than the number of pods - but probably never bigger.
So for services something between /16 and /24 (but not /12 which would be more services than pods ;-)).

**Comment by r0ckarong** [comment]
@ereslibre What would be the correct values here?

**Comment by ereslibre** [comment]
There are no "correct" values. This depends on the cluster planning design and is entirely up to the user.

The default pod subnet is `10.244.0.0/16`, what is a sensible default. It allows for 65536 pods overall. Assignment of CIDR's is by default /24 per node, so you still have a limit of 256 IP addresses per node.

Depending on the size of the nodes that you are planning to use (in terms of resources), or on the number of nodes you are planning to have you could increase the CIDR per node to something bigger, but you would then be able to fit less nodes.

Example:

- With `10.244.0.0/16` you have:
  - 65536 IP addresses (not that number of pods globally, since on each range we can't count with `.0`, `.1`, and `.255`).
  - If you are using the default node allocation of /24, you can fit 256 nodes maximum, because you can fit 256 `/24` ranges in a `/16` range.

Depending if you want more or less pods per node, or if you are planning to have a high number of nodes you might want to tweak this settings.

Same goes for the service subnet, this subnet should not overlap with the pod CIDR, and it should be big enough for all your services to fit in there. We have some defaults, but the user should be able to plan this beforehand depending on their needs.
