### ISSUE TITLE
[doc] 4.5.3.1.2  Update the Authentication Connector - do not use kubectl edit

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#671]
4.5.3.1.2  Update the Authentication Connector

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_sec.admin.security.rbac.update

-------

From a best practice point of view we should never use kubectl edit.

Could we change this to "adjust yaml and apply yaml"?

**Comment by r0ckarong** [comment]
@cclhsu Why was kubectl chosen here? Can we simply replace this with changing the yaml file?

**Comment by innobead** [comment]
This should be only for runtime change when @cclhsu worked on this documentation. However dex is part of addon, so it would be better to change the addon manifest  then apply instead of runtime only by `kubectl edit`. So this turns out @Martin-Weiss question.

@cclhsu please help evaluate then change the doc if need. Thanks.

**Comment by cclhsu** [comment]
I believe we encountered one scenario [591](https://github.com/SUSE/doc-caasp/pull/591) when addon upgrade where yaml in ~/clusters/<CLUSTER_NAME> is not consisted with resource in running cluster.  In such cases, user required to download the existing oidc-dex-config ConfigMap before addon upgrade, then re-apply the downloaded oidc-dex-config ConfigMap after addon upgraded. Or just simply edit the config as current document does.

**Comment by Martin-Weiss** [comment]
We should never recommend to use "edit" as this causes the deployments to be "non-immutable" and "non-reproducible" anymore.
But yes - there is a problem that the skuba addon yaml files get updated once we do a skuba addon upgrade. This is still an open point where engineering is working on (I believe the idea is to use kustomize in the future..)

**Comment by innobead** [comment]
Yes as @Martin-Weiss said, there is an on-going effort about kustomize to have merge strategy when upgrading new addons with skuba. (ref: https://github.com/SUSE/skuba/pull/858)

Also understand @cclhsu said, but even we ask user to modify addon manifest, that is still not a source of true, because it's just located in an operator's workstation w/ single copy and w/o any version control (ex: skuba does have gitops DNA yet). 

So I would suggest to do below for a workaround for the current situation.

1. for any addon manifest update, guide user update the manifest in cluster definition folder then apply. 
2. remind user before upgrading addons, need to backup the current ones at runtime, then restore w/ modification back after upgrading because of known addon update limitation

**Comment by Martin-Weiss** [comment]
3. ensure the gangway secret and the dex secret config match!

I have seen that for some reason the gangway secret changed and re-applying the old dex secret config will break authentication in case the secret in the configmap changed in the meantime..

**Comment by r0ckarong** [comment]
Closed with #712

**Comment by innobead** [comment]
JFYI, kustomize just getting merged in skuba master branch, so it means there will be some improvement in the future and doc updated.
