### ISSUE TITLE
[doc] 7.1.4  Deployment

### ISSUE THREAD

**Issue by tgeek77** [SUSE/doc-caasp#764]
7.1.4  Deployment

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-admin/#_deployment

In the minimal working setup command, it might be best to add "--namespace kube-system" or else the rsyslog pods will be created in the default namespace.

**Comment by r0ckarong** [comment]
@innobead Could you please confirm that the kube-system namespace is the right place for these pods?

**Comment by tgeek77** [comment]
I think creating an rsyslog namespace and putting it there could be acceptable also, but I don't think the default namespace is a good idea for default.

**Comment by Martin-Weiss** [comment]
> 
> 
> I think creating an rsyslog namespace and putting it there could be acceptable also, but I don't think the default namespace is a good idea for default.

I would not create one namespace per application / per daemon set etc. 
IMO the rsyslog stuff should go to the kube-system namespace per default.

**Comment by innobead** [comment]
Don't see any reason to install in `kube-system` but we can improve this by adding `--namespace` to align with other helm chart installation in the documentation like `--namespace logging`

cc @cclhsu can you help with this. Thanks.

**Comment by Martin-Weiss** [comment]
> 
> 
> Don't see any reason to install in `kube-system` but we can improve this by adding `--namespace` to align with other helm chart installation in the documentation like `--namespace logging`.

Because kube-system namespace already exists and it does not make much sense to create a namespace per single deployment or per single daemon set.

(pretty similar to a filesystem where you also do not create one sub-directory per file ;-)).

"Grouping" most often makes sense if you need separate rights or restrictions.. - so in case we add additional "logging components" one day like ELK and we need delegated administration for that objects - a separate namespace would make sense.

Or do I miss something?

> 
> cc @cclhsu can you help with this. Thanks.

**Comment by innobead** [comment]
> > Don't see any reason to install in `kube-system` but we can improve this by adding `--namespace` to align with other helm chart installation in the documentation like `--namespace logging`.
> 
> Because kube-system namespace already exists and it does not make much sense to create a namespace per single deployment or per single daemon set.
> 
> (pretty similar to a filesystem where you also do not create one sub-directory per file ;-)).
> 
> "Grouping" most often makes sense if you need separate rights or restrictions.. - so in case we add additional "logging components" one day like ELK and we need delegated administration for that objects - a separate namespace would make sense.
> 
> Or do I miss something?
> 
> > cc @cclhsu can you help with this. Thanks.

Theoretically what you said makes sense but it's still not a solid reason, because `kube-system` is for kuberentes system components or our builtin addons. All helm charts we provide are for extensibility so it's better to explain in a purposed namespace. 

However, we can do that change for sure if this can simplify the adoption/understanding from users :) but that means we also need to check again if we have similar examples in the existing documentation and need to have a minor adjustment for consistency.

**Comment by Martin-Weiss** [comment]
True - maybe we have to add a chapter to the docs explaining the sense and best practice for namespaces so enable them to decide themselves.

We have nginx-ingress, prometheus, grafana, kubernetes-dashboard, log-agent-rsyslog, metrics-server, nfs-client-provisioner, velero,.... and it is basically the question about delegated administration and probably also resources management how to split the applications in a cluster among one or multiple namespaces and how to define which ones are used for what.
As with the example for "subdirectories vs files" - the same "fun" needs to be discussed for namespaces and will be individual per customer.

**Comment by jenting** [comment]
As #773 merged, closing issue.
