### ISSUE TITLE
[doc] 2  Cluster Management - graceful shutdown and startup procedure missing

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#774]
2  Cluster Management

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_cluster_management

---------------------------------
From time to time it is required to do a full shutdown of the system - i.e. in case there are storage operations or network operations or virtualization operations having an operational risk for the cluster or the applications running within the cluster.

For such a situation we have to give customers an advice how to graceful shutdown everything and after the shutdown start up all in the correct order.

From what I have in mind this might be a starting point for discussion:

1. document the current scale of applications (stateful sets, deployments)
    (kubectl get ..)
2. shutdown the application ( kubectl scale --replicas=0 ) for all running applications
3. drain all the workers and wait until no pods are running anymore (only deamonsets are ok to run)
4. shutdown the workers (in parallel or sequential?)
5. shutdown the masters (in parallel or sequential?)
6. shutdown the admin machine / surrounding services like load balancer, ldap, registry etc.

Now do the operations required in network/storage/virtualization etc.

1. Power on the admin machine and surrounding services (load balancer, ldap, registry)
2. Power on the masters (all in parallel or sequential)?
3. Power on the workers (all in parallel or sequential)?
4. verify that the cluster is up and running properly (kube-dns, etcd,....)
5. scale the deployments and stateful sets to the original scale before the shutdown

RFC ;-).

**Comment by r0ckarong** [comment]
This was originally part of the Admin Guide RFC but wasn't prioritized so far.
The old backlog item is this:
https://github.com/SUSE/doc-caasp/issues/329

@ereslibre @flavio @kkaempf @qnetter

**Comment by ereslibre** [comment]
The approach as a super safe way to stop your whole cluster looks fine to me. However, I wonder if this is really necessary.

When there are workloads running, and you shutdown your machine, these workloads will already be terminated by the system by a SIGTERM, right? So in theory, the cleanup will be graceful. I don't know at what time a SIGKILL might be sent if the SIGTERM is not timely. I also don't know if in this case the configured graceful shutdown period is respected somehow.

In my opinion, if there is evidence where one has ended with inconsistent workload storage for example because of this, then I think we should push for this, otherwise I don't see a big advantage in following this procedure.

If the system is already shutdown in a graceful way without having to scale to 0, drain, shutdown, power up, uncordon, rescale to original, I would not include this; mainly because this will involve a complete shutdown of all the running applications for a period of time, leaving a fairly wide window for downtime.

**Comment by ereslibre** [comment]
> How do we avoid "failover" or "new scheduled work" during the cluster shutdown with lots of applications?

What I'm going to propose should be double checked,

1. Cordon all nodes. Do not drain them.
2. Shutdown machines. Either all of them at the same time if you don't care about downtime, or in groups in sequence -- keeping an eye that your workloads are replicated across different nodes.
3. Perform maintenance operation.
4. Start all machines or the subset of machines that you powered off.
5. After having finished with all machines (either in one go, or all subgroups), uncordon all nodes.

I would expect that this operation will avoid rescheduling of pods, since all nodes are cordoned, and so the scheduler won't be able to reschedule anything. At the same time, the machine will just take everything as it was before it was shutdown when it comes back.

> How can we guarantee a proper shutdown?
> Just initiate "poweroff" on all workers and masters in a sequential or parallel way?

I would say there's the same level of certainty on the two options: drain or shutting down the machine. Draining will also try to first kill processes in a graceful way, and turn to a forceful way after a given time. So, I don't see a big advantage in draining.

Also, it's important to note that scaling everything to 0 and draining might not always be possible, for example if pod disruption budgets are set (that our customers should by the way). They would need to also alter the pod disruption budgets and then set everything back to normal afterwards, what I believe is pretty cumbersome.

> Sometimes it takes very long until process stop - especially if you stop multiple in parallel and you have 100 PODs on one worker..

This depends on the configured grace deletion time, and I would expect this time to be the same on both approaches (e.g. running a `shutdown -h now` and a `kubectl drain` or a scale to 0).

> Maybe we need an operator that can do all the work of "stop all applications, power off, power on, start all applications".

I honestly have serious doubts this can be done at all in a correct way, and ensuring all possible cases (like the disruption budget mentioned before).

Do we know how others are recommending this procedure?

**Comment by Martin-Weiss** [comment]
So basically we are in agreement - the only left question might be application dependent. 
(scale to 0 or not, before you shutdown).

I see that scaling down reduces the load slowly and allows better handling of concurrent actions that might cause a high load during shutdown (concurrent disk IO during closing the application).
After the reboot - nothing is producing load and the load can be slowly increased again by increasing the scale slowly. (depending on the maintenance changes - you have a chance to see i.e. network problems or storage problems etc. before the system might be under full load.

Honestly I really would love to see a "pause" or "stop/start" on deployments/statefulsets that would allow to stop and start applications temporarily without the need to change the replication settings.

**Comment by r0ckarong** [comment]
@kkaempf Rafa wrote "What I'm going to propose should be double checked,". Who can do that? This is keeping me from adding this to the docs in any meaningful way.

**Comment by kkaempf** [comment]
> @kkaempf Rafa wrote "What I'm going to propose should be double checked,". Who can do that?

@flavio and @dirkmueller come to mind.

**Comment by dirkmueller** [comment]
Sorry @kkaempf I have no meaningful prior experience on this topic.

I can do some googling om this over the next few days. I think the original ask was to check Rafa's recommend procedure. I think that could be done by testing it.

**Comment by kkaempf** [comment]
Adding @fgerling to provide QA capabilities.

**Comment by ereslibre** [comment]
> I think that could be done by testing it.

I agree with @dirkmueller. QA or an engineer can check that it works as expected. I can help in whatever is needed, but don't have the cycles at the moment to try it out myself entirely.

**Comment by evrardjp** [comment]
We should just propose the drain and the operation on the node. It's by far simpler, and that's what recommended in the kubernetes world. Not sure what you want to avoid. It's even what's done with kured, so it's consistent with our testing.

Just drain, do you operation on your hardware, restart.
Drain cordons, so I think that's enough. If you want to avoid rescheduling you should probably not use kubernetes in the first place.

**Comment by evrardjp** [comment]
See also: https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/ , https://kubernetes.io/docs/concepts/workloads/pods/disruptions/ , and https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/#maintenance-on-a-node

**Comment by evrardjp** [comment]
We can indeed QA this, but that wouldn't be far from testing kured's behaviour.

**Comment by ereslibre** [comment]
> We should just propose the drain and the operation on the node

In the context of this card (shutting down the whole system), if it's at once, I would not recommend draining, because it will generate a storm of rescheduling of everything running in the cluster. Also, drains will honor the pod disruption budgets.

I think that if you know beforehand that you want to stop the whole system it's better to not drain and follow an approach similar to https://github.com/SUSE/doc-caasp/issues/774#issuecomment-617804308.

**Comment by evrardjp** [comment]
I missed the "full" part.

**Comment by evrardjp** [comment]
Agreed with Rafa's comment on the "full shutdown" story.

I think in the context of our documentation, it's probably worth explaining when to do the drain and cordon (which are explained at the bottom of the section https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#node_operations), respectively for a partial cluster graeceful shutdown, and for a full shutdown.

**Comment by evrardjp** [comment]
@r0ckarong do you need further help on this?

**Comment by r0ckarong** [comment]
> @r0ckarong do you need further help on this?

Yes, I need someone to fully verify that these steps work and give me detailed step-by-step instructions how to perform the procedures.

> * Cordon all nodes. Do not drain them.
> * Shutdown machines. Either all of them at the same time if you don't care about downtime, or in groups in sequence -- keeping an eye that your workloads are replicated across different nodes.
> * Perform maintenance operation.
> * Start all machines or the subset of machines that you powered off.
> * After having finished with all machines (either in one go, or all subgroups), uncordon all nodes.

And, in my opinion, we need someone from QA to create test cases around this so these instructions are perdiodically verified and tested.

**Comment by kkaempf** [comment]
> And, in my opinion, we need someone from QA to create test cases around this so these instructions are perdiodically verified and tested.

@r0ckarong please talk to @fgerling when he's back next week if/how to approach this.

**Comment by fgerling** [comment]
Thanks @r0ckarong for mentioning test cases. I added the issue to the QA Project. We can come up with a case and verify the steps from https://github.com/SUSE/doc-caasp/issues/774#issuecomment-617804308.

**Comment by r0ckarong** [comment]
> > And, in my opinion, we need someone from QA to create test cases around this so these instructions are perdiodically verified and tested.
> 
> @r0ckarong please talk to @fgerling when he's back next week if/how to approach this.

I still need someone to pick this up and produce the instructions.

**Comment by r0ckarong** [comment]
Somewhat related: https://github.com/SUSE/avant-garde/issues/1808

**Comment by evrardjp** [comment]
@mssola this card is for a full shutdown, not a partial shutdown. Your PR is valuable, but doesn't fix the issue here.

**Comment by r0ckarong** [comment]
Relates to #329

**Comment by evrardjp** [comment]
Can we close this card?
