### ISSUE TITLE
[doc] 3.1.1  Basic SSH Key Configuration - key with ed25519 instead of ecdsa, timeout for ssh-agent

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#820]
3.1.1  Basic SSH Key Configuration

https://susedoc.github.io/doc-caasp/master/single-html/caasp-deployment/#ssh.configuration

------------------------

Why do we recommend to use ed25519 instead of ecdsa? I thought ecdsa is the new sles default?

For loading the ssh-agent we should add a timeout to expire loaded keys for security reasons!

So could we change: 

`eval "$(ssh-agent)"`

to timeout 1 hour:

`eval "$(ssh-agent -t 3600)"`

**Comment by r0ckarong** [comment]
@ereslibre @kkaempf Who can answer the question about the choice of cipher?

Do we have any technical reasons not to implement agent timeout?

**Comment by kkaempf** [comment]
> @ereslibre @kkaempf Who can answer the question about the choice of cipher?
> 
> Do we have any technical reasons not to implement agent timeout?

@jsegitz should be best suited to answer security question within CaaSP.

**Comment by jenting** [comment]
cc @dannysauer

**Comment by dannysauer** [comment]
Sorry - I missed the tag. :)

ed25519 is slightly faster than ecdsa, but no one will actually notice that. They're both eleptic curve algorithms and quite good; mathematically they're essentially the same in terms of theoretical security, and both better than prime factor based algorithms in about every possible way.

The ecdsa signing algorithm (curve P-256) has been around longer (in ssh, especially) and is, as a result, more broadly compatible. That makes it a good general purpose default for the OS.  However, ed25519 has a number of subtle implementation advantages, including the implementation explicitly preventing various side channel attacks. http://ed25519.cr.yp.to/ describes it a bit more. There is also a curve comparison at https://safecurves.cr.yp.to/, if deeper reading or general reasons to argue with DJ Bernstein are desired. Everyone loves arguing with DJB. :D 

Curve 25519 is also not a US NIST-developed curve with tinfoil hat back doors like curve P-256, for people who suspect such unlikely things. ;)

Anyway, because the CAASP endpoints are going to both be the same version of SLES supporting the same algorithms, "broad comparability" is irrelevant. As such, I suggested ed25519 as the best signing algorithm to use when generating a key for CaaSP.

**Comment by dannysauer** [comment]
For a timeout, that's really a site-specific security measure related to things like shell inactivity. If we do suggest a timeout, I'd do it on the `ssh-add` instead of the agent. Some people will use an alternate agent, like gpg-agent or their desktop keyring / wallet. By doing the timeout on the `ssh-add`, we help all users rather than just those using the openssh agent. :)

How do we pick a timeout, though? How many nodes are being added in a script after adding the key; are they all done in an hour? Fifteen minutes? An 8 hour workday? 🤷‍♂️

**Comment by Martin-Weiss** [comment]
Thanks for the feedback!

Regarding ssh-key - I really believe this is some sort of a religion and at least we should have this identical within SUSE for all the products (SLES/SES/SUMA/CaaSP....) and I see ed25519 in CaaSP the first and only time.

Regarding the timeout - I believe we should have the timeout per default and skuba should also prompt for re-adding the key in case it times out during the deployment. At least in the examples we should have the timeout added to the agent AND the ssh-add, then.

**Comment by dannysauer** [comment]
I'd be inclined to say that troubleshooting might be easier with customers if we were only proposing a timeout in one place. I'm also a little hesitant to propose things that have potential impact outside of our product. :) Personally, I don't like timeouts on stuff like that at all; my experience is that it leads to complacency, and that the timeout still leaves plenty of time for compromise. So that may color my opinion.

For the key type, I'm not in marketing, so my opinion is that simply using ecliptic curve is a sufficient win. If someone at a higher pay grade than me likes everything the same, I won't argue; ecdsa isn't a bad thing. I just think ed25519 is a slightly better thing. ;)

**Comment by dannysauer** [comment]
PR for the agent/add timeout documentation opened.  Rather than dictate a default timeout, I thought adding a note about the security impact would work out better in the common case, while users who have concerns can heed the warning.  Feel free to disagree in the PR discussion. :D

**Comment by dannysauer** [comment]
I did a bit more digging, and asked the "official" security group.  The most compelling argument I've heard so far is that ecdsa is a FISP-approved DSS algorithm, while ed25519 is not yet (it's in [a draft proposal](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf) right now, though).  I can't find an avant-garde issue talking about FIPS compliance, but I know that's something we're considering for CaaSP.  As such, maybe we should switch the example to use ecdsa.  Probably also should add a note that rsa and ed25519 also are supported, but ecdsa is the best eliptic curve algorithm with FIPS compatibility.

It might be worth spending some time looking at the SLES documentation to see if there's anything similar in there that we can copy verbiage from or link to for the sake of consistency.  I'll try to do that in the next couple of days.

**Comment by dannysauer** [comment]
The SLES ssh documentation is at https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-ssh.html
Do you have any thoughts on how to work that link into `adoc/deployment-preparation.adoc`, @r0ckarong ?

**Comment by r0ckarong** [comment]
> The SLES ssh documentation is at https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-ssh.html
> Do you have any thoughts on how to work that link into `adoc/deployment-preparation.adoc`, @r0ckarong ?

@dannysauer There shouldn't be any special things to be considered. The separate product guides don't "interlink" in any way so this would be handled like any ordinary external(to the document) link.

**Comment by dannysauer** [comment]
> @dannysauer There shouldn't be any special things to be considered. The separate product guides don't "interlink" in any way so this would be handled like any ordinary external(to the document) link.

Sorry, @r0ckarong - I meant I wasn't sure where to put the link. It seems awkward to me to add it anywhere in this section about keys. :/
