### ISSUE TITLE
[doc] 9.1.2.1  Procedure - invalid escape characte detected for the backslash here: /backup/etcd-snapshot-\$(date +%Y-%m-%d_%H:%M:%S_%Z).db

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#862]
9.1.2.1  Procedure:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_procedure

----
had to change this: /backup/etcd-snapshot-\$(date +%Y-%m-%d_%H:%M:%S_%Z).db

to this: /backup/etcd-snapshot-$(date +%Y-%m-%d_%H:%M:%S_%Z).db

--> not sure why in your case the backslash worked..

**Comment by jenting** [comment]
cc @c3y1huang

**Comment by c3y1huang** [comment]
@Martin-Weiss the backslash is by purpose and use to escape the `$` in `cat` command for generating the manifest. Without it will put the actual time in the manifest instead of `$(date +%Y-%m-%d_%H:%M:%S_%Z)`
```
cat << *EOF* > ${MANIFEST}
...
*EOF*
```
If you've manually copied the content instead of using `cat` then yes you will need to remove the backslash.
