### ISSUE TITLE
[doc] 4.10.4.1  Prerequisites - message: secret/oidc-gangway-cert not labeled

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#885]
4.10.4.1  Prerequisites:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_prerequisites_2

----------------
```
caaspadm@caasp4-01:~/caasp4/suse.cert-exporter> kubectl label --overwrite secret oidc-dex-cert -n kube-system caasp.suse.com/skuba-addon=true
kubectl label --overwrite secret oidc-gangway-cert -n kube-system caasp.suse.com/skuba-addon=true
kubectl label --overwrite secret metrics-server-cert -n kube-system caasp.suse.com/skuba-addon=true
secret/oidc-dex-cert not labeled
caaspadm@caasp4-01:~/caasp4/suse.cert-exporter> kubectl label --overwrite secret oidc-gangway-cert -n kube-system caasp.suse.com/skuba-addon=true
secret/oidc-gangway-cert not labeled
caaspadm@caasp4-01:~/caasp4/suse.cert-exporter> kubectl label --overwrite secret metrics-server-cert -n kube-system caasp.suse.com/skuba-addon=true
secret/metrics-server-cert not labeled
```

--> why do I get the message "not labeled"?

**Comment by jenting** [comment]
I think it's due to skuba `4.2.1` helps to label the secret for you.

We added the prerequisites to the user is because the cert-exporter is delivered by helm-chart, which means it can be run on all Kubernetes versions we delivered.
If the user deploys a cluster with skuba `4.2.0` and the user want to install cert-exporter to monitors the certificate, then the user must do the prerequisites to let cert-exporter know which certificates are addons.

**Comment by Martin-Weiss** [comment]
Ok - then we should at least inform the admin that he might see the message "not lableled". (getting an error message might make admins nervous ;-))

**Comment by jenting** [comment]
sure~

**Comment by r0ckarong** [comment]
@jenting If you create a PR in response to an issue, please use the "Link Issue/PR" feature in the sidebar. This makes attributing this easier while tracking and also closes the issue when merging PR through the GH interface. Automation keywords are great for closing this on the Git CLI but for project tracking please also link the PR issues.

/cc @innobead
