### ISSUE TITLE
[doc] 1.4.1  Sub-Network Sizing

### ISSUE THREAD

**Issue by phakkarainen** [SUSE/doc-caasp#987]
1.4.1  Sub-Network Sizing:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-deployment/#_sub_network_sizing

"The **default** pod subnet is 10.244.0.0/**16**. It allows for 65536 IP addresses overall. Assignment of CIDR’s is **by default /24** (254 usable IP addresses per node)."

**Comment by r0ckarong** [comment]
Could you please provide more information about what change to the documentation you expect? You added some emphasis on these parts of the text but what am I supposed to do here?

**Comment by phakkarainen** [comment]
Sorry for the confusion. 

From the text I get impression there's only one network. Yet there are two masks /24 and /16.
I still think that there should be two networks (pods and nodes) with separate masks.

Pete

**Comment by r0ckarong** [comment]
@kkaempf @ereslibre @mdarnell-suse 
Do we actually have to separate networks here? Suggestions on how we can communicate this better?

**Comment by mdarnell-suse** [comment]
I'll weigh in with my opinion, but I'd like to have @rktidwell verify.

The answer for me is that yes, we need two networks. The first network is the host or API network. These are the IP addresses assigned to the primary NIC on all of the Kubernetes nodes.

The second network is the generally non-routable IP subnet provided to the Kubernetes cluster, and all pod IP addresses are issued from this subnet. It can be as small as a /24, but doing so means you have a maximum of 253 (or thereabouts) pods for the entire cluster. Changing it to a /16 as suggested above is probably a good move.

What would make this better communicated? Verbiage as I've provided in this comment, but in the context of a simple graphic which shows the nodes with pods in them, the two different subnets documented at the top of the diagram, and sample IPs assigned to both nodes and pods would probably make this pretty clear to a reasonably competent administrator.

**Comment by Martin-Weiss** [comment]
We also should be very clear about the size for the POD and the size of the Services network. I still miss the point why the default for the services network is "bigger" than the network for PODs. I really believe the number of services would always be lower than the number of PODs - or do I miss something? ;-).

**Comment by rktidwell** [comment]
I've read and re-read this section of documentation several times, and the understanding I walk away with is that this is simple subnetting exercise. We supply a /16 for the entire cluster, and because the default node CIDR is a /24 we can support 256 nodes with the default out-of-the-box configuration. The cluster network is a private network that is generally not routable (there are exceptions, but these are not common). That's what this section is describing. The 2 subnet masks make perfect sense: the /16 is the larger block from which we are carving the CIDR's that actually are used by the individual nodes in the cluster. In and of themselves, I don't see how referencing a /16 and a /24 indicates multiple networks here. Maybe we can make the documentation clearer by being more explicit about how this is a simple exercise in subnetting.

However, Mark brings a good point regarding completeness of the documentation. When you step back and look at the architecture of a cluster, there are indeed two networks. The first being the cluster network (which is described in the docs referenced here) and the second being the "public" network that provides the "last mile" connectivity to each node in the cluster.

I agree that some graphics might be useful here when discussing both the subnetting exercise for the cluster network and the overall picture of a deployed cluster.
