### ISSUE TITLE
[doc] 13.4  Deployment

### ISSUE THREAD

**Issue by dsohk** [SUSE/doc-caasp#992]
13.4  Deployment:

https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_deployment_2

Is there any velero deployment setup/configuration guide using SES (SUSE Enterprise Storage) as backup object storage provider?

**Comment by r0ckarong** [comment]
https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#_object_storage_and_its_credentials

If you scroll past the section about the Public Cloud Providers you will find a section "S3-Compatible Providers" that links to the relevant SES docs.

I have reworked this section in the next build so that it becomes a distinct item in the navigation and makes it clearer where to find it.

**Comment by dsohk** [comment]
That’s great! Thank you for pointing out and re-organizing it to stand out the use of SES as velero backup storage provider.
