### ISSUE TITLE
[doc] 5  Upgrading SUSE CaaS Platform - structure.. move update/upgrade from admin guide to deployment guide

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#995]
5  Upgrading SUSE CaaS Platform:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_upgrading_suse_caas_platform

------
To be discussed:

I would expect update/upgrade instructions in the deployment guide and not in the release-notes or the admin guide.
What do you think? Could we have "install, update and upgrade" moved into the "deployment" guide?

**Comment by r0ckarong** [comment]
The way the documents were meant is:

Deployment - Initial planning, installation and rollout
Admin - Daily operations and maintenance

Upgrading, to me, is part of maintenance and not a separate rollout and that's why upgrading is part of the admin guide.

The release notes will contain release specific upgrade instructions occasionally. I don't want to re-write the update instructions for each release if it's only a very temporary change (only needed for one release). Basically you would perform the "regular" update procedure as detailed in the admin guide and then have additional information for special procedures that apply to that particular update.

**Comment by Martin-Weiss** [comment]
Looking and many other product documentations - installation and upgrade are part of the deployment guides - that is why I was requesting this change.. 

Daily patching/operations is right in the admin guide but should be also linked from the deployment guide as all servers should always be patched before doing an upgrade.

**Comment by r0ckarong** [comment]
> Looking and many other product documentations - installation and upgrade are part of the deployment guides - that is why I was requesting this change..

Out of curiosity, could you give me some examples? Maybe I can better understand how others are structuring this if this is the way you would prefer.

I'll have a look how badly the procedures are entangled in the admin guide so I could move them.

**Comment by Martin-Weiss** [comment]
SLES and SUSE Manager have separate upgrade guides
SES https://documentation.suse.com/ses/6/single-html/ses-deployment/#ses-deployment
Open Enterprise Server https://www.novell.com/documentation/open-enterprise-server-2018/oes_implement_lx/data/bookinfo.html

I believe many product documentations have the deployment document with install and upgrade.. 

Regarding the release notes.. these were the source for update/upgrade of minor releases in 4.0..4.2.3 - but to be honest - also these update / upgrade instructions should have been in the deployment/install/update/upgrade guide..

**Comment by r0ckarong** [comment]
With where the product is heading it makes little sense to introduce such a drastic change at this time.
